# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: justfortest
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: new-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-service-3

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
